set(_CATKIN_CURRENT_PACKAGE "centerpoint")
set(centerpoint_VERSION "0.0.0")
set(centerpoint_MAINTAINER "nvidia <nvidia@todo.todo>")
set(centerpoint_PACKAGE_FORMAT "2")
set(centerpoint_BUILD_DEPENDS "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(centerpoint_BUILD_EXPORT_DEPENDS "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(centerpoint_BUILDTOOL_DEPENDS "catkin")
set(centerpoint_BUILDTOOL_EXPORT_DEPENDS )
set(centerpoint_EXEC_DEPENDS "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(centerpoint_RUN_DEPENDS "pcl_ros" "roscpp" "sensor_msgs" "std_msgs")
set(centerpoint_TEST_DEPENDS )
set(centerpoint_DOC_DEPENDS )
set(centerpoint_URL_WEBSITE "")
set(centerpoint_URL_BUGTRACKER "")
set(centerpoint_URL_REPOSITORY "")
set(centerpoint_DEPRECATED "")